name: Copy File to Local

on:
  workflow_dispatch:

jobs:
  copy_file:
    runs-on: windows-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Copy File to Local
      run: |
        curl -LJQ https://github.com/ClydeLiu1/studio4-chatbot-project/raw/main/About.txt
           |xcopy About.txt C:\laragon\www

