name: Copy File

on:
  push:
    branches:
      - main

jobs:
  copy-file:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Copy file to local directory
        run: |
          $destination = "C:\laragon\www"
          Copy-Item -Path "github.com/ClydeLiu1/studio4-chatbot-project/blob/main/About.txt" -Destination $destination -Force
