name: Copy File to Local

on:
  workflow_dispatch:

jobs:
  copy_file:
    runs-on: windows-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Copy File to Local
      run: |
        cp github.com/ClydeLiu1/studio4-chatbot-project/blob/main/About.txt C:\laragon\www
