name: Download and Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Download file
        uses: actions/download-artifact@v2
        with:
          name: artifact-name
          path: C:\laragon\www


